development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI") %>
      options:
        server_selection_timeout: 5
        connect_timeout: 10
        socket_timeout: 5
        max_pool_size: 10
        min_pool_size: 1
        wait_queue_timeout: 5
        retry_writes: true